### ISSUE TITLE
Use cookies instead of database for cart

### ISSUE THREAD

**Issue by Volkanite** [Volkanite/catropolis#23]
@Huan-Ting you made an excellent effort trying to get the cart to work with a database, but until we properly implement a sign-in system, I think it would be easier to work with cookies instead of a database. I'll implement it in a new branch so you can see how it works before we merge to master.

**Comment by Huan-Ting** [comment]
Hi Hakim, I'm not sure about that, do you know that so far when a user type in his or her name at the beginning, the person can retrieve the cats that he or she already adopted before by saving a user name in cookies? Actually it's already a kind of sign-in system just without authentication. And It means if we implement a formal sign-in system with authentication, we don't have to change anything of cart function, all we have to do is when we implement the formal sign-in system (with authentication), we add a line saving the user name in cookies, and whole system can integrate.

**Comment by Huan-Ting** [comment]
It takes a long time to accomplish a database-cart-function 😅 Sorry about that I am quite busy during these day😅   So far database-cart-function seems to work ok, although I will have to add a 'if statement' to avoid user add the same cat twice...   SO AND BUT, YES we can work with cookies instead of a database OF COURSE, just make sure that we are on the same page :)  BTW, R u going to work on this project after Monday 8:00am?

**Comment by Volkanite** [comment]
Okay, I was only making the suggestion because the delete function was giving some problems. And yes, I'll keep working on the project after Monday. I'll keep working on it until every issue is fixed.

**Comment by Huan-Ting** [comment]
Morning, Hakim, cart function seems completed, could you help me to check? And, If cart has no more bug, I think you can change the connected DB to your account, it will easier for you to build other functions. What do you think?

**Comment by Volkanite** [comment]
Yes, the cart is working properly. I'll leave the current DB for now and change it later if I need to.
